name: copy_repos_workflow
on: 
    workflow_dispatch:
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    create_repo:
        runs-on: ubuntu-latest
        container:
            image: python:3.11.11
        steps:
            - name: checkout_repos
              uses: actions/checkout@v4

            - name: check_dir
              run: ls -lah

            - name: set_up_python_environment
              run: |
                   pip install --upgrade pip && \
                   pip install -r requirements.txt &&\
                   pip list

            - name: run_python_script
              run: |
                    chmod 750 main.py &&\
                    ./main.py